// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9yXlsTKfShp8hWhnR_Qg9G8AqBVxZTqY',
    appId: '1:821259364563:web:063a6b39bd98be0fe90c26',
    messagingSenderId: '821259364563',
    projectId: 'shelfcontrol-8f5ab',
    authDomain: 'shelfcontrol-8f5ab.firebaseapp.com',
    storageBucket: 'shelfcontrol-8f5ab.firebasestorage.app',
    measurementId: 'G-MM00KDH703',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyf3S8E98oGJZEsuLgIAb4TEfXGzCJvpE',
    appId: '1:821259364563:android:cafb8514b4fca833e90c26',
    messagingSenderId: '821259364563',
    projectId: 'shelfcontrol-8f5ab',
    storageBucket: 'shelfcontrol-8f5ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJB_1cgKYE01W0Y7Lyy3_6A15IFXlfncg',
    appId: '1:821259364563:ios:09c5584b521c22f7e90c26',
    messagingSenderId: '821259364563',
    projectId: 'shelfcontrol-8f5ab',
    storageBucket: 'shelfcontrol-8f5ab.firebasestorage.app',
    iosBundleId: 'com.luisenriquez.shelfcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJB_1cgKYE01W0Y7Lyy3_6A15IFXlfncg',
    appId: '1:821259364563:ios:81fe0a065dc5c949e90c26',
    messagingSenderId: '821259364563',
    projectId: 'shelfcontrol-8f5ab',
    storageBucket: 'shelfcontrol-8f5ab.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9yXlsTKfShp8hWhnR_Qg9G8AqBVxZTqY',
    appId: '1:821259364563:web:dbe3ccd96742e2c6e90c26',
    messagingSenderId: '821259364563',
    projectId: 'shelfcontrol-8f5ab',
    authDomain: 'shelfcontrol-8f5ab.firebaseapp.com',
    storageBucket: 'shelfcontrol-8f5ab.firebasestorage.app',
    measurementId: 'G-BM6EYWZTWV',
  );
}
