import firebase_admin
from firebase_admin import credentials, firestore
import csv
import os
import re

# --- Configuration ---
SERVICE_ACCOUNT_KEY_PATH = 'scripts/serviceAccountKey.json' 
# Use the enriched CSV file generated by process_csvs.py
CSV_FILE_PATH = 'scripts/enriched_products_with_diet.csv' 
FIRESTORE_COLLECTION_NAME = 'local_products_ph'

# --- Initialize Firebase ---
try:
    if not os.path.exists(SERVICE_ACCOUNT_KEY_PATH):
        raise FileNotFoundError(f"Service account key not found at: {SERVICE_ACCOUNT_KEY_PATH}")
    
    cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
    if not firebase_admin._apps: # Initialize only if not already initialized
        firebase_admin.initialize_app(cred)
    db = firestore.client()
    print("Firebase initialized successfully.")
except Exception as e:
    print(f"Error initializing Firebase: {e}")
    exit()

# --- Delete Collection Function ---
def delete_collection(coll_ref, batch_size):
    docs = coll_ref.limit(batch_size).stream()
    deleted = 0

    for doc in docs:
        print(f"Deleting doc {doc.id} => {doc.to_dict()}")
        doc.reference.delete()
        deleted = deleted + 1

    if deleted >= batch_size:
        return delete_collection(coll_ref, batch_size)

# --- Upload CSV Data to Firestore ---
def upload_csv_to_firestore(csv_path, collection_name, clear_existing=False):
    if clear_existing:
        print(f"Clearing existing collection '{collection_name}'...")
        delete_collection(db.collection(collection_name), 100) # Use a smaller batch size for deletion
        print(f"Finished clearing collection '{collection_name}'.")

    print(f"Starting upload from {csv_path} to Firestore collection '{collection_name}'...")
    batch = db.batch()
    batch_size = 500 # Firestore batches have a limit of 500 operations

    try:
        with open(csv_path, mode='r', encoding='utf-8') as file:
            csv_reader = csv.DictReader(file)
            
            # Get header names and clean them (e.g., remove BOM if present)
            fieldnames = [field.strip().replace('\ufeff', '') for field in csv_reader.fieldnames]
            csv_reader.fieldnames = fieldnames

            for i, row in enumerate(csv_reader):
                # Ensure required columns exist from the enriched CSV
                required_columns = ['productName', 'netWeight', 'price', 'category', 'subcategory', 'search_keywords', 'source', 'locale', 'dietary_tags', 'allowed_diets']
                if not all(key in row for key in required_columns):
                    print(f"Skipping row {i+1} due to missing required columns: {row}")
                    continue

                # Prepare data for Firestore - directly use values from enriched_products.csv
                product_data = {
                    'productName': row['productName'].strip(),
                    'netWeight': row['netWeight'].strip(),
                    'price': float(row['price'].strip()),
                    'category': row['category'].strip(),
                    'subcategory': row['subcategory'].strip(),
                    'search_keywords': [k.strip() for k in row['search_keywords'].split(',') if k.strip()], # Convert to array
                    'source': row['source'].strip(),
                    'locale': row['locale'].strip(),
                    'dietary_tags': [t.strip() for t in row.get('dietary_tags', '').split(',') if t.strip()], # Convert to array, handle if column doesn't exist
                    'allowed_diets': [d.strip() for d in row.get('allowed_diets', '').split(',') if d.strip()] # Convert to array
                }
                
                doc_ref = db.collection(collection_name).document() 
                batch.set(doc_ref, product_data)

                if (i + 1) % batch_size == 0:
                    batch.commit()
                    batch = db.batch()
                    print(f"Committed {i + 1} documents.")
            
            # Commit any remaining documents in the last batch
            if (i + 1) % batch_size != 0:
                batch.commit()
                print(f"Committed final {i + 1} documents.")
        
        print(f"Successfully uploaded all products from {csv_path} to Firestore collection '{collection_name}'.")

    except FileNotFoundError:
        print(f"Error: CSV file not found at {csv_path}")
    except KeyError as e:
        print(f"Error: Missing expected column in CSV: {e}. Please ensure all required columns exist in {csv_path}.")
    except ValueError as e:
        print(f"Error converting data type: {e}. Check 'price' column for non-numeric values.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    CLEAR_EXISTING_COLLECTION = True 
    upload_csv_to_firestore(CSV_FILE_PATH, FIRESTORE_COLLECTION_NAME, clear_existing=CLEAR_EXISTING_COLLECTION)
